### ISSUE TITLE
[Staff] workspaces 設定による node_modules 内エラーの対応（analysis_options.yaml の除外設定）

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2025#109]
### 担当チーム
Infra

### 概要
workspaces に `apps/website` を指定したことで、`node_modules` 内でエラーが発生しています。

### 対応案
`analysis_options.yaml` をプロジェクト直下に配置し、以下のように `node_modules` ディレクトリを除外することで解決できそうです。

```yaml
analyzer:
  exclude:
    - "node_modules"
```

📝 .npmignore や package.json の files フィールドでは解決しなかった。
