### ISSUE TITLE
[Staff] Deno lint, fmt のワークフローを作成する

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2025#42]
## 概要
リポジトリのコード品質を維持するために、Deno の lint と fmt のワークフローを GitHub Actions で実装します。

### 担当チーム

Infra

### 実装内容

※ `deno lint` は `md`, `json`, `jsonc`, `yaml` に対して効果がなさそうだったため省略

- [x] `deno.jsonc` を作成する
  - fmt の設定を記述する
- [x] `.github/workflows/wc-check-style-deno.yaml` を作成する
  - [mise-action](https://github.com/jdx/mise-action) を使用して Deno のセットアップを行う
  - 以下のような設定を想定:
    ```yaml
    - uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11
      with:
        install_args: "deno"
    ```
- [x] Deno の fmt チェックを実装する
  - PR 作成時に実行されるようにする
  - フォーマットが正しくない場合は PR をブロックする
- [x] deno fmt を実行してコミットする
  - 既存コードに fmt を適用
  - 変更をコミットして PR を作成

### 期待される効果

- コードの一貫性が保たれる
- コード品質の維持が自動化される
- レビュープロセスが効率化される

## 参考文献
- [Deno CLI Commands - lint](https://docs.deno.com/runtime/manual/tools/linter)
- [Deno CLI Commands - fmt](https://docs.deno.com/runtime/manual/tools/formatter)
- [GitHub Actions - Deno](https://github.com/denoland/setup-deno)
- [Deno Configuration File](https://docs.deno.com/runtime/manual/getting_started/configuration_file)
- [mise-action](https://github.com/jdx/mise-action)
